# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Publish npm package to GitHub Packages
on:
  release:
    types: [created]
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      id: checkout
          
    - name: Set up Node 20
      uses: actions/setup-node@v3
      with:
        cache-dependency-path: web/angular/
        node-version: 20
        cache: 'npm'
        registry-url: https://registry.npmjs.org/

    - name: Cache NPM packages
      uses: actions/cache@v3
      with:        
        path: '~/.npm'
        key: ${{ runner.os }}-${{ matrix.node-version }}-9.8.0-npmcache-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install angular cli
      working-directory: web/angular/
      run: npm install -g @angular/cli@latest

    - name: Publish
      env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_REPOSITORY_TOKEN}}
      working-directory: web/angular/
      run: npm run publish
